title: 송윤희(Power BI MVP) | Power BI & Copilot 강의·컨설팅
description: Power BI, Microsoft Copilot 등 Microsoft 기술 강의, 개발, 집필을 진행하는 1인기업 홈페이지입니다.
lang: ko

email: unisong114@gmail.com

url: "https://songyunhee.netlify.app"
repository: unisong114/MainPage

markdown: kramdown
plugins:
  - jekyll-feed

collections:
  lectures:
    output: true
    permalink: /lectures/:path/
  books:
    output: true
    permalink: /books/:path/

defaults:
  - scope:
      path: ""
      type: "lectures"
    values:
      layout: "lecture"
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
